stages:
  - name: 入职培训
    actions:
      - name: 学习工艺知识库
        emotion: 0
      - name: 查看案例，提问
        emotion: -1

  - name: 工艺设计
    actions:
      - name: 工位明细、工艺流程设计
        emotion: -2
        # 痛点：300页协议包含32种特殊业务场景[1](@ref)
        # AI优化：NLP生成交互式知识图谱[3](@ref)
      - name: 绘制装配指导书
        emotion: -1

  - name: 审核应用
    actions:
      - name: 根据评审意见修改
        emotion: -1
        # AI优化：LSTM模型自动生成预测代码框架[3](@ref)
      - name: 现场装配执行
        emotion: 2
      - name: 出现突发问题
        emotion: -1



  - name: 知识沉淀
    actions:
      - name: 提交多仓库协同模块PR
        emotion: 0
        # 痛点：微服务事务冲突需三次架构调整[1](@ref)
      - name: 收到K8s资源配额预警
        emotion: -1
